### ISSUE TITLE
iOS: Error evaluating injectedJavaScript

### ISSUE THREAD

**Issue by chrisgenao** [KittyCookie/react-native-chartjs#12]
I've been checking on this error and im not able to fix it, the error is:

> "Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string. Error Domain=WKErrorDomain Code=4 "A JavaScript exception ocurred"
> UserInfo ={WKJavaScriptExceptionLineNumber=0, WKJavaScriptExceptionMessage=, WKJavaScriptExceptionColumnNumber=0, NSLocalizedDescription=A JavaScript exception occurred}

I've been checking inside the library and everything is working perfectly, even in Android, it's working correctly.

**Comment by bboure** [comment]
@chrisgenao @KittyCookie 
I am regularly getting this error too.
Any fix? or workaround?

THanks

**Comment by chrisgenao** [comment]
@bboure @KittyCookie found the solution, it was due to chartjs using an old version of react-native-webview, all you got to do is:

1. install last version of react-native-webview
2. go to node_modules copy react-native-webview and go to react-native-chartjs inside node_modules.
3. Inside react-native-chartjs in node_modules, you will find a folder called node_modules, which will contain an old instance of react-native_webview, delete it or rename it.
4. Paste in here the copy of react-native-webview that is updated to lastest version.
5. Fixed.

Hope it helps you and others.

**Comment by bboure** [comment]
@chrisgenao I tried updating `react-native-webview` but now I get another error. 
"requireNativeComponent: "RNCWebView" was not found in the UIManager"
Apparently, [this is an Expo issue](https://github.com/react-native-community/react-native-webview/issues/140)

Do you use Expo or did you eject?

**Comment by SodaisNasir** [comment]
Hi guys I am trying to run Javascript inside react-native-webview. Its working fine on Android however, in IOs its giving this 

Error:evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string. Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=0, WKJavaScriptExceptionMessage=Cannot execute JavaScript in this document, WKJavaScriptExceptionColumnNumber=0, NSLocalizedDescription=A JavaScript exception occurred}


Any ideas on how to execute JS methods which are already inside a file?
